from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import random
ran = random.randrange(10000)
driver = webdriver.Firefox()
driver.get("https://www.google.com/intl/es-419/gmail/about/")
link = driver.find_element_by_xpath('/html/body/header/div/div/div/a[3]/span[2]')
link.click()
element = driver.find_element(By.CSS_SELECTOR, "#firstName")
element.send_keys("Nicolas maduro32")
element.send_keys(Keys.TAB)
#all_options = element.find_elements(By.TAG_NAME,"option")
#for option in all_options:
#    print("Value is: %s" % option.get_attribute("value"))
#    option.click()
element = driver.find_element(By.CSS_SELECTOR,"#lastName")
element.send_keys("Perez")
element.send_keys(Keys.TAB)
element = driver.find_element(By.CSS_SELECTOR,"#username")
element.send_keys("nicomaduro"+str(ran))
element.send_keys(Keys.TAB)
element = driver.find_element(By.NAME,("Passwd"))
element.send_keys("Z0013497BD3D9p3p")
element.send_keys(Keys.TAB)
element = driver.find_element(By.CSS_SELECTOR,("#confirm-passwd > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > input:nth-child(1)"))
element.send_keys("Z0013497BD3D9p3p")
element.send_keys(Keys.TAB)
element.send_keys(Keys.TAB)
element = driver.find_element(By.CSS_SELECTOR,(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > span:nth-child(4)"))
element.click()
element = driver.find_element(By.CSS_SELECTOR,("#phoneNumberId"))
element.send_keys("17642934122")
element = driver.find_element(By.CSS_SELECTOR,(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > span:nth-child(4)"))
element.click()
